env:
  node: true
  commonjs: true
  es6: true
  browser: true
  jest: true
parserOptions:
  ecmaVersion: 2017
rules:
## BEGIN ESLint Defaults
  no-await-in-loop:
    - error
  no-compare-neg-zero:
    - error
  no-cond-assign:
    - error
  no-constant-condition:
    - error
  no-control-regex:
    - error
  no-dupe-args:
    - error
  no-dupe-keys:
    - error
  no-duplicate-case:
    - error
  no-empty:
    - error
  no-empty-character-class:
    - error
  no-ex-assign:
    - error
  no-extra-boolean-cast:
    - error
  no-extra-semi:
    - error
  no-func-assign:
    - error
  no-inner-declarations:
    - error
  no-invalid-regexp:
    - error
  no-irregular-whitespace:
    - error
  no-obj-calls:
    - error
  no-regex-spaces:
    - error
  no-sparse-arrays:
    - error
  no-template-curly-in-string:
    - error
  no-unexpected-multiline:
    - error
  no-unreachable:
    - error
  no-unsafe-finally:
    - error
  no-unsafe-negation:
    - error
  use-isnan:
    - error
  valid-typeof:
    - error
  dot-notation:
    - error
  no-case-declarations:
    - error
  no-empty-pattern:
    - error
  no-extra-bind:
    - error
  no-global-assign:
    - error
  no-octal:
    - error
  no-redeclare:
    - error
  no-self-assign:
    - error
  no-unused-labels:
    - error
  no-useless-escape:
    - error
  no-undef:
    - error
  no-unused-vars:
    - error
  no-mixed-spaces-and-tabs:
    - error
## END ESLint Defaults
  no-console:
    - off
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  curly:
    - error
  eqeqeq:
    - error
    - always
  strict:
    - error
    - global
  space-in-parens:
    - error
    - always
  no-var:
    - error
  semi-spacing:
    - error
  no-caller:
    - error
  no-return-assign:
    - error
  no-debugger:
    - warn
  keyword-spacing:
    - error
  key-spacing:
    - error
    - beforeColon: false
  space-before-blocks:
    - error
  space-infix-ops:
    - error
  object-curly-spacing:
    - error
    - always
  comma-spacing:
    - error
  no-trailing-spaces:
    - error
